<?php

require_once dirname(__FILE__) . '/../../models/product.php';

/**
 * Test class for Product.
 * Generated by PHPUnit on 2012-05-12 at 16:47:29.
 */
class ProductTest extends PHPUnit_Framework_TestCase
{
	public function validProducts()
	{
		return array(
			array(1, "PID-12345", 2.35, 20),
			array(2, "PID-12346", 2.75, 20),
		);
	}

	public function invalidProducts()
	{
		return array(
			array(null, "PID-12345", 2.35, 20),
			array(2, null, 2.75, 20),
		);
	}

	/**
	 * @dataProvider validProducts
	 */
	public function testValidProduct($id=null, $code=null, $price=0, $stock=0)
	{
		$result = new Product($id, $code, $price, $stock);
		$this->assertGreaterThan(0, $result->stock_qty);
		$this->assertGreaterThan(0, $result->unit_price);
		$this->assertTrue(is_string($result->product_code));
	}

	/**
	 * @expectedException ProductCreationException
	 * @expectedExceptionMessage Unable to create product
	 * @dataProvider invalidProducts
	 */
	public function testInvalidProduct($id=null, $code=null, $price=0, $stock=0)
	{
		$result = new Product($id, $code, $price, $stock);
		$this->assertGreaterThan(0, $result->stock_qty);
		$this->assertGreaterThan(0, $result->unit_price);
		$this->assertTrue(is_string($result->product_code));
	}

	/**
	 * @covers Product::has_stock
	 */
	public function testHas_stock()
	{
		$result = new Product(1, "PID-12345", 2.35, 20);
		$this->assertTrue($result->has_stock());

		$result = new Product(1, "PID-12345", 2.35, 0);
		$this->assertFalse($result->has_stock());
		$result->stock_qty += 15;
		$this->assertTrue($result->has_stock());
	}

}

?>